[package]
name = "TD6"
version = "0.1.0"
edition = "2024"

[dependencies]
rand_core = {version = "0.9.3", features = ["std"]}
rand = "0.8"
ed25519-dalek = {version = "2", features = ["rand_core"]}
sha3 = "0.11.0-pre.5"
hex = "0.4.3"
