[package]
name = "TD6"
version = "0.1.0"
edition = "2024"

[dependencies]
rand_core = {version = "0.9.3", features = ["std"]}
rand = "0.8"
x25519-dalek = {version = "2.0.1", features = ["static_secrets"]}
chacha20poly1305 = "0.10.1"
sha3 = "0.10.8"
hex = "0.4.3"
